# The embed to send.
embed:
  # Should the embed be enabled?
  enabled: true
  # Should the response be silent?
  silent: true
  # The embed title.
  title: "Example"
  # Author settings, If text is blank. do nothing.
  author:
    # The text i.e. author name.
    text: ""
    # The icon.
    url: ""
  # The thumbnail, which shows up on the right side of the embed.
  thumbnail: ""
  # The image, which shows up at the bottom of the embed.
  image: ""
  # The embed description.
  description:
    - "The embed description"
  # The embed fields.
  fields:
    "1":
      # The title of the field.
      title: "Default"
      # The body of the field.
      body:
        - "This is an example."
      # Should the field be inline?
      inline: false
    "2":
      # The title of the field.
      title: "Default x2"
      # The body of the field.
      body:
        - "This is another example."
      # Should the field be inline?
      inline: false
  # The embed footer.
  footer:
    # Should the footer be enabled?
    enabled: true
    # Should we fall back on the user who ran the command, if no values below are found?
    user-fallback: true
    # The timezone.
    timezone: "America/New_York"
    # Should a timestamp be added?
    timestamp: false
    # The value for the footer, if blank. user is used instead.
    value: ""
    # The value for the footer icon, if blank. we will ignore it.
    icon: ""
  # The color of the embed.
  color: "#FCFCFC"